CREATE TABLE towns(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(45) NOT NULL
);

CREATE TABLE stadiums(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(45) NOT NULL,
	capacity INT NOT NULL,
	CHECK (capacity > 0),
	town_id INT NOT NULL REFERENCES towns ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE teams(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(45) NOT NULL,
	established DATE NOT NULL,
	fan_base INT DEFAULT 0 NOT NULL,
	CHECK (fan_base >= 0),
	stadium_id INT NOT NULL REFERENCES stadiums ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE coaches(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(10) NOT NULL,
	last_name VARCHAR(20) NOT NULL,
	salary NUMERIC(10, 2) DEFAULT 0 NOT NULL,
	CHECK (salary >= 0),
	coach_level INT DEFAULT 0 NOT NULL,
	CHECK (coach_level >= 0)
);

CREATE TABLE skills_data(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	dribbling INT DEFAULT 0 NOT NULL,
	CHECK (dribbling >= 0),
	pace INT DEFAULT 0,
	CHECK (pace >= 0),
	passing INT DEFAULT 0,
	CHECK (passing >= 0),
	shooting INT DEFAULT 0,
	CHECK (shooting >= 0),
	speed INT DEFAULT 0,
	CHECK (speed >= 0),
	strength INT DEFAULT 0,
	CHECK (strength >= 0)
);

CREATE TABLE players(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(10) NOT NULL,
	last_name VARCHAR(20) NOT NULL,
	age INT DEFAULT 0 NOT NULL,
	CHECK (age >= 0),
	position CHAR(1) NOT NULL,
	salary NUMERIC(10, 2) DEFAULT 0 NOT NULL,
	CHECK (salary >= 0),
	hire_date TIMESTAMP,
	skills_data_id INT NOT NULL REFERENCES skills_data ON DELETE CASCADE ON UPDATE CASCADE,
	team_id INT REFERENCES teams ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE players_coaches(
	player_id INT REFERENCES players ON DELETE CASCADE ON UPDATE CASCADE,
	coach_id INT REFERENCES coaches ON DELETE CASCADE ON UPDATE CASCADE
);
